### ISSUE TITLE
Missing l10n inside the mod...

### ISSUE THREAD

**Issue by FirenzeIT** [modelleicher/FS22_realismAddon_fillables#15]
Hello @modelleicher, something is missing inside the mod, please fix them for future updates (ITA language FS22). Thank you.
 
28.11.23 Warning: Missing l10n 'input_REALISM_ADDON_FILLABLES_LOCALONOFF' in mod 'FS22_realismAddon_fillables'

![1248130_20231128213320_1](https://github.com/modelleicher/FS22_realismAddon_fillables/assets/113168067/b3888a9c-976a-43b5-99dc-6c5de59f910c)

**Comment by FirenzeIT** [comment]
Hello @modelleicher, something is missing inside the mod, please fix them for future updates (ITA language FS22). Thank you.
 
28.11.23 Warning: Missing l10n 'input_REALISM_ADDON_FILLABLES_LOCALONOFF' in mod 'FS22_realismAddon_fillables'

![1248130_20231128213320_1](https://github.com/modelleicher/FS22_realismAddon_fillables/assets/113168067/b3888a9c-976a-43b5-99dc-6c5de59f910c)

**Comment by KITT3000** [comment]
#10

**Comment by FirenzeIT** [comment]
> #10

Perfect, thank you very much 💯 For now it's all ok.
